### ISSUE TITLE
Color Scheme - globals

### ISSUE THREAD

**Issue by jrappen** [meetio-theme/scheme-generator#3]
A list of current global keys for Color Schemes:

```text
background
foreground
invisibles
caret
block_caret
block_caret_border
block_caret_underline
block_caret_corner_radius
block_caret_corner_style
line_highlight

misspelling
fold_marker
minimap_border
accent

popup_css
phantom_css
sheet_css

gutter
gutter_foreground
gutter_foreground_highlight

line_diff_width
line_diff_added
line_diff_modified
line_diff_deleted

selection
selection_foreground
selection_border
selection_border_width
inactive_selection
inactive_selection_border
inactive_selection_foreground
selection_corner_style
selection_corner_radius

highlight
find_highlight
find_highlight_foreground

scroll_highlight
scroll_selected_highlight

rulers

guide
active_guide
stack_guide

brackets_options
brackets_foreground
bracket_contents_options
bracket_contents_foreground

tags_options
tags_foreground

shadow
shadow_width
```

You seem to be missing a few?

Compare:

<https://www.sublimetext.com/docs/color_schemes.html>

For the three `*_css` compare:

<https://www.sublimetext.com/docs/minihtml.html>

You can also force the `*ish` colors by defining them in Color Scheme globals:

<https://www.sublimetext.com/docs/minihtml.html#predefined-variables>

**Comment by mauroreisvieira** [comment]
Hey @jrappen thanks for the report, about the missing keys for Color Schemes is updated ([interface](https://github.com/meetio-theme/scheme-generator/blob/master/lib/interfaces.ts#L174)), but regarding the `*_css` and `*ish` I don't get your point, can you explain your idea?

**Comment by jrappen** [comment]
Phantoms mainly used in build systems to show build errors, popups mainly LSP or any plugin using the mdpopups dependency. (miniHTML-) Sheets are ST4065+ and used by the Changelog and currently very few plugins.

`*-ish` colors should usually default to the closest scheme color of a given named `*-ish` color, for example `redish` should result in the most red palette color of your scheme. But you can force it to a certain (other) value.

**Comment by jrappen** [comment]
Also, all values in the globals section are strings, even those with an implied integer value. But I see you already figured that out.

**Comment by mauroreisvieira** [comment]
Ok, so @jrappen are you suggesting something like that [schemeGenerator](https://github.com/meetio-theme/scheme-generator/blob/master/lib/scheme/schemeGenerator.ts#L53)?

by default will assign a color for `*-ish` based on the defined color, but also allow to customize the color, by passing it as a parameter.

As a final results, we have something like: [Scheme Exampe](https://github.com/meetio-theme/scheme-generator/blob/master/schemes/Meetio%20Scheme%20Example.sublime-color-scheme#L15)

**Comment by jrappen** [comment]
@mauroreisvieira Yeah.

---

If you compare this to Mariana, you can see that bluish might or migh not be what would be expected:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/8577450/202465015-6b2c8acf-0cf1-4a79-990e-63117cb078a7.png">

**Comment by mauroreisvieira** [comment]
From what I can see, Mariana does not use bluish color. 
So from the scheme generator what I can do?

**Comment by jrappen** [comment]
Example:

Sublime Text will use blue (i.e. `hsl(240,100%,50%)`) or a color close to that if your Color Scheme provides one. In other words [it will guess](https://www.sublimetext.com/docs/minihtml.html#predefined-variables). The result of that guess might not be what you had intended, though. You might prefer another hue. So you can override that via `bluish`.

**Comment by mauroreisvieira** [comment]
Ok, but with the current approach of the scheme generator, will set default colors for `*-ish` based on base colors, but allow a possibility to set your own color for `*-ish`.

So what exactly we can do on our side, part of that?

By the way, will receive a string, so you can use HEX, HSL, or others, supported by ST.

**Comment by jrappen** [comment]
It's fine that way.
