### ISSUE TITLE
Syntax highlighting on GitHub

### ISSUE THREAD

**Issue by jrappen** [meetio-theme/scheme-generator#4]
This should fix highlighting:

```bash
# ./.gitattributes

*.sublime-color-scheme      linguist-language=JSON-with-Comments
*.hidden-color-scheme       linguist-language=JSON-with-Comments

*.hidden-tmTheme            linguist-language=XML-Property-List
```

when viewing on GitHub.

Reference:

<https://github.com/github/linguist/blob/master/lib/linguist/languages.yml>

Not sure if this caching issue (github/linguist#4496) still exists, though.

/cc FYI @facelessuser

**Comment by facelessuser** [comment]
@jrappen  So, editing `.gitattributes` allows GitHub to highlight unrecognized file extensions? I assume that is what this is insinuating?

**Comment by jrappen** [comment]
@facelessuser yessir

**Comment by mauroreisvieira** [comment]
Thanks, @jrappen for your contribution.
